// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        action: string;
        btnInner: string;
        btnRd: string;
        btnRdLarge: string;
        btnRdSmall: string;
        card: string;
        cardText: string;
        countdown: string;
        home: string;
        pie: string;
        pieCenter: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
