// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ButtonCssNamespace {
    export interface IButtonCss {
        btn: string;
        btnInner: string;
    }
}

declare const ButtonCssModule: ButtonCssNamespace.IButtonCss;

export = ButtonCssModule;
