// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace RoundCssNamespace {
    export interface IRoundCss {
        active: string;
        btn: string;
    }
}

declare const RoundCssModule: RoundCssNamespace.IRoundCss;

export = RoundCssModule;
